<link href="{{asset('general/img/favicon.png')}}" rel="icon">
  <link href="{{asset('general/img/apple-touch-icon.png')}}" rel="apple-touch-icon">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="{{asset('general/vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{asset('general/vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">
  <link href="{{asset('general/css/style.css')}}" rel="stylesheet">